<a href="https://colab.research.google.com/github/divyasuresh1450-ai/Python-For-Data-Science-/blob/main/practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name:Divya Suresh Gaikwad
Roll no:SY-A -64

Practical no:2

AIM:To acquire the dataset from a CSV file and perform data cleaning operations such as checking null values, duplicates, and datasetstructure using Python Pandas

In [1]:
from google.colab import files
uploaded = files.upload()

Saving aistudent.csv to aistudent.csv

In [2]:
import pandas as pd
df = pd.read_csv("aistudent.csv")
print(df)

     Student_ID  Age  Gender Education_Level        City AI_Tool_Used  \
0             1   15  Female         College   Hyderabad      Copilot
1             2   21  Female      University     Chennai      Copilot
2             3   22    Male      University   Bangalore       Gemini
3             4   22    Male         College   Hyderabad      ChatGPT
4             5   22    Male         College   Hyderabad       Gemini
..          ...  ...     ...             ...         ...          ...
395          96   16  Female          School      Multan    Grammarly
396          97   25  Female          School  Faisalabad       Gemini
397          98   17  Female         College  Faisalabad       Gemini
398          99   15  Female         College      Lahore    Notion AI
399         100   24  Female          School      Multan       Gemini

     Daily_Usage_Hours   Purpose Impact_on_Grades Satisfaction_Level
0                  1.1  Learning   Slight Decline             Medium
1                  1.7    Coding   Slight Decline               High
2                  1.5  Learning         Improved                Low
3                  3.8  Research         Improved                Low
4                  5.2    Coding   Slight Decline                Low
..                 ...       ...              ...                ...
395                5.0  Learning   Slight Decline             Medium
396                1.9   Writing        No Change             Medium
397                2.9   Writing        No Change                Low
398                3.6  Homework   Slight Decline               High
399                2.7  Learning         Improved               High

[400 rows x 10 columns]

In [3]:
print
(df.head())

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
0,1,15,Female,College,Hyderabad,Copilot,1.1,Learning,Slight Decline,Medium
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
2,3,22,Male,University,Bangalore,Gemini,1.5,Learning,Improved,Low
3,4,22,Male,College,Hyderabad,ChatGPT,3.8,Research,Improved,Low
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low

In [4]:
print
(df.tail())

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
395,96,16,Female,School,Multan,Grammarly,5.0,Learning,Slight Decline,Medium
396,97,25,Female,School,Faisalabad,Gemini,1.9,Writing,No Change,Medium
397,98,17,Female,College,Faisalabad,Gemini,2.9,Writing,No Change,Low
398,99,15,Female,College,Lahore,Notion AI,3.6,Homework,Slight Decline,High
399,100,24,Female,School,Multan,Gemini,2.7,Learning,Improved,High

In [5]:
print
(df.shape)

(400, 10)

In [6]:
print
(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Education_Level', 'City',
       'AI_Tool_Used', 'Daily_Usage_Hours', 'Purpose', 'Impact_on_Grades',
       'Satisfaction_Level'],
      dtype='object')

In [7]:
print
(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          400 non-null    int64
 1   Age                 400 non-null    int64
 2   Gender              400 non-null    object
 3   Education_Level     400 non-null    object
 4   City                400 non-null    object
 5   AI_Tool_Used        400 non-null    object
 6   Daily_Usage_Hours   400 non-null    float64
 7   Purpose             400 non-null    object
 8   Impact_on_Grades    400 non-null    object
 9   Satisfaction_Level  400 non-null    object
dtypes: float64(1), int64(2), object(7)
memory usage: 31.4+ KB

In [8]:
print
(df.isnull().
sum
())

Student_ID            0
Age                   0
Gender                0
Education_Level       0
City                  0
AI_Tool_Used          0
Daily_Usage_Hours     0
Purpose               0
Impact_on_Grades      0
Satisfaction_Level    0
dtype: int64

In [9]:
print
(df.duplicated().
sum
())

np.int64(0)

In [10]:
df = df.drop_duplicates()
print
(df)

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
0,1,15,Female,College,Hyderabad,Copilot,1.1,Learning,Slight Decline,Medium
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
2,3,22,Male,University,Bangalore,Gemini,1.5,Learning,Improved,Low
3,4,22,Male,College,Hyderabad,ChatGPT,3.8,Research,Improved,Low
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low
...,...,...,...,...,...,...,...,...,...,...
395,96,16,Female,School,Multan,Grammarly,5.0,Learning,Slight Decline,Medium
396,97,25,Female,School,Faisalabad,Gemini,1.9,Writing,No Change,Medium
397,98,17,Female,College,Faisalabad,Gemini,2.9,Writing,No Change,Low
398,99,15,Female,College,Lahore,Notion AI,3.6,Homework,Slight Decline,High
399,100,24,Female,School,Multan,Gemini,2.7,Learning,Improved,High

In [11]:
print
(df.describe())

       Student_ID         Age  Daily_Usage_Hours
count  400.000000  400.000000         400.000000
mean   125.500000   19.425000           2.933750
std     87.906592    2.991948           1.589939
min      1.000000   15.000000           0.500000
25%     50.750000   17.000000           1.575000
50%    100.500000   19.500000           2.900000
75%    200.250000   22.000000           4.200000
max    300.000000   25.000000           6.000000

In [12]:
print
(df[
"Age"
].mean())

np.float64(19.425)

In [13]:
print
(df[
"Daily_Usage_Hours"
].
max
())

6.0

In [14]:
print
(df[
"Daily_Usage_Hours"
].
min
())

0.5

In [15]:
print
(df[
"Gender"
].value_counts())

Gender
Male      205
Female    195
Name: count, dtype: int64

In [16]:
print
(df[
"City"
].value_counts())

City
Delhi         37
Bangalore     32
Chennai       32
Jaipur        32
Pune          30
Kolkata       30
Lucknow       29
Multan        29
Ahmedabad     28
Hyderabad     27
Mumbai        23
Lahore        22
Islamabad     18
Faisalabad    17
Karachi       14
Name: count, dtype: int64

In [17]:
print
(df[
"AI_Tool_Used"
].value_counts())

AI_Tool_Used
Gemini       129
ChatGPT      124
Copilot      108
Grammarly     24
Notion AI     15
Name: count, dtype: int64

In [18]:
print
(df[df[
"Purpose"
] ==
"Coding"
])

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low
5,6,17,Male,College,Delhi,ChatGPT,1.0,Coding,No Change,Low
6,7,15,Female,School,Pune,Copilot,4.5,Coding,Slight Decline,High
10,11,22,Male,School,Jaipur,ChatGPT,4.4,Coding,No Change,Medium
...,...,...,...,...,...,...,...,...,...,...
374,75,16,Male,University,Lahore,Grammarly,4.0,Coding,Slight Decline,Low
376,77,19,Female,College,Islamabad,ChatGPT,5.7,Coding,Improved,Medium
384,85,25,Female,College,Islamabad,Notion AI,1.7,Coding,No Change,High
385,86,19,Male,College,Karachi,Gemini,0.5,Coding,No Change,Low
392,93,21,Male,School,Multan,Notion AI,2.4,Coding,Improved,High

In [19]:
print
(df[df[
"Age"
] >
20
])

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
2,3,22,Male,University,Bangalore,Gemini,1.5,Learning,Improved,Low
3,4,22,Male,College,Hyderabad,ChatGPT,3.8,Research,Improved,Low
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low
10,11,22,Male,School,Jaipur,ChatGPT,4.4,Coding,No Change,Medium
...,...,...,...,...,...,...,...,...,...,...
392,93,21,Male,School,Multan,Notion AI,2.4,Coding,Improved,High
393,94,21,Female,School,Islamabad,Grammarly,3.9,Homework,Improved,Low
394,95,23,Male,School,Multan,Gemini,5.0,Research,Improved,High
396,97,25,Female,School,Faisalabad,Gemini,1.9,Writing,No Change,Medium
399,100,24,Female,School,Multan,Gemini,2.7,Learning,Improved,High

In [20]:
print
(df[[
"Age"
,
"Gender"
,
"AI_Tool_Used"
]])

     Age  Gender AI_Tool_Used
0     15  Female      Copilot
1     21  Female      Copilot
2     22    Male       Gemini
3     22    Male      ChatGPT
4     22    Male       Gemini
..   ...     ...          ...
395   16  Female    Grammarly
396   25  Female       Gemini
397   17  Female       Gemini
398   15  Female    Notion AI
399   24  Female       Gemini

[400 rows x 3 columns]

In [21]:
print
(df[df[
"Age"
] >
20
])

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
2,3,22,Male,University,Bangalore,Gemini,1.5,Learning,Improved,Low
3,4,22,Male,College,Hyderabad,ChatGPT,3.8,Research,Improved,Low
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low
10,11,22,Male,School,Jaipur,ChatGPT,4.4,Coding,No Change,Medium
...,...,...,...,...,...,...,...,...,...,...
392,93,21,Male,School,Multan,Notion AI,2.4,Coding,Improved,High
393,94,21,Female,School,Islamabad,Grammarly,3.9,Homework,Improved,Low
394,95,23,Male,School,Multan,Gemini,5.0,Research,Improved,High
396,97,25,Female,School,Faisalabad,Gemini,1.9,Writing,No Change,Medium
399,100,24,Female,School,Multan,Gemini,2.7,Learning,Improved,High

In [22]:
print
(df[[
"Age"
,
"Gender"
,
"AI_Tool_Used"
]])

     Age  Gender AI_Tool_Used
0     15  Female      Copilot
1     21  Female      Copilot
2     22    Male       Gemini
3     22    Male      ChatGPT
4     22    Male       Gemini
..   ...     ...          ...
395   16  Female    Grammarly
396   25  Female       Gemini
397   17  Female       Gemini
398   15  Female    Notion AI
399   24  Female       Gemini

[400 rows x 3 columns]

In [23]:
print
(df.sort_values(
"Age"
))

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
18,19,15,Male,School,Kolkata,ChatGPT,2.6,Writing,Slight Decline,Medium
24,25,15,Male,University,Delhi,Gemini,4.8,Learning,Slight Decline,Medium
31,32,15,Female,University,Chennai,Gemini,2.2,Coding,Slight Decline,Low
27,28,15,Female,School,Pune,Copilot,0.5,Research,Slight Decline,High
372,73,15,Male,University,Faisalabad,Notion AI,4.7,Homework,No Change,Low
...,...,...,...,...,...,...,...,...,...,...
350,51,25,Female,University,Faisalabad,Notion AI,1.9,Research,Improved,Medium
337,38,25,Female,School,Faisalabad,ChatGPT,0.7,Coding,Improved,Low
380,81,25,Female,University,Lahore,ChatGPT,0.6,Learning,Improved,Medium
353,54,25,Female,School,Islamabad,Grammarly,2.5,Research,No Change,Medium
355,56,25,Female,School,Karachi,Notion AI,2.2,Learning,Slight Decline,High

In [24]:
print
(df[df[
"Purpose"
] ==
"Coding"
])

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
1,2,21,Female,University,Chennai,Copilot,1.7,Coding,Slight Decline,High
4,5,22,Male,College,Hyderabad,Gemini,5.2,Coding,Slight Decline,Low
5,6,17,Male,College,Delhi,ChatGPT,1.0,Coding,No Change,Low
6,7,15,Female,School,Pune,Copilot,4.5,Coding,Slight Decline,High
10,11,22,Male,School,Jaipur,ChatGPT,4.4,Coding,No Change,Medium
...,...,...,...,...,...,...,...,...,...,...
374,75,16,Male,University,Lahore,Grammarly,4.0,Coding,Slight Decline,Low
376,77,19,Female,College,Islamabad,ChatGPT,5.7,Coding,Improved,Medium
384,85,25,Female,College,Islamabad,Notion AI,1.7,Coding,No Change,High
385,86,19,Male,College,Karachi,Gemini,0.5,Coding,No Change,Low
392,93,21,Male,School,Multan,Notion AI,2.4,Coding,Improved,High

1.
What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion andcleaning?
Data ingestion is the process of collecting and importing data from different sources such as CSV files, Excel files, databases, APIs, orwebsites into a system for further analysis.It brings raw data into a usable format,Helps in storing and organizing data,Makes data readyfor analysis and machine learning,Ensures data from multiple sources can be combined.The most commonly used Python library for dataingestion and cleaning is Pandas.


2.Why is data cleaning necessary before performing analysis or machine learning?
Data cleaning is necessary because real-world data often contains:Missing values,Duplicate records Incorrect values,Inconsistentformats,Extra spaces or unwanted symbols. If data is not cleaned:Results may be incorrect Model accuracy decreases,Analysis becomesmisleading.


3.How do you load a CSV file into a Pandas DataFrame?
A CSV file can be loaded using the read_csv() function.
import pandas as pd
df = pd.read_csv("aistudent.csv") print(df)


4.
What is the difference between head() and tail() functions in Pandas?
Both functions are used to preview data. head():Displays the first 5 rows of the dataset by default. print(df.head()) tail():Displays the last 5rows of the dataset by default. print(df.tail()) Example: head() : top rows tail() : bottom rows these are useful for quickly checking thedataset structure.


5.
How can you identify missing values in a dataset?
Missing values can be identified using: isnull() isna() Example: print(df.isnull()):To count missing values in each column:print(df.isnull().sum()) This shows the number of missing values column-wise.